name: lick_ice_cream
description: The Offical App for the Lick Ice Creamery

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  equatable: ^2.0.5
  apple_maps_flutter: ^1.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bloc: ^7.2.0
  flutter_lints: ^1.0.0
  flutter_svg: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - example.png
    - ice_cream_cone.png
    - ice_cream_icon.png
    - choclate.png
    - strawberry_cheesecake.png
    - location_screenshot.png
