name: testing
description: Testing Pubsepc

publish_to: 'none'

version: 2.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

#dependency_overrides:
#  wft_lib_theme:
#    ##    path: "" # Add you local package path if you want to test locally
#    git:
#      ref: develop
#      url: "https://github.com/one-thd/wft_lib_theme.git"
#  wft_lib_tool_translations:
#    ##    path: "" # Add you local package path if you want to test locally
#    git:
#      ref: develop
#      url: "https://github.com/one-thd/wft_lib_tool_translations.git"
#
dependencies:
  flutter:
    sdk: 2.0.1

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  equatable: ^2.0.5
  apple_maps_flutter: ^1.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bloc: ^7.2.0
  flutter_lints: ^1.0.0
  flutter_svg: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - example.png
    - ice_cream_cone.png
    - ice_cream_icon.png
    - choclate.png
    - strawberry_cheesecake.png
    - location_screenshot.png
"0": "{"
"1": "\"version\": \"2.0.1\","
"2": "\"dependencies.flutter.sdk\": \"2.0.1\""
"3": "}"
"4": '"'
"5": v
"6": e
"7": r
"8": s
"9": i
"10": o
"11": n
"12": '"'
"13": ":"
"14": " "
"15": '"'
"16": "2"
"17": .
"18": "0"
"19": .
"20": "1"
"21": '"'
"22": ","
"23": "\n"
"24": " "
"25": " "
"26": '"'
"27": d
"28": e
"29": p
"30": e
"31": n
"32": d
"33": e
"34": n
"35": c
"36": i
"37": e
"38": s
"39": .
"40": f
"41": l
"42": u
"43": t
"44": t
"45": e
"46": r
"47": .
"48": s
"49": d
"50": k
"51": '"'
"52": ":"
"53": " "
"54": '"'
"55": "2"
"56": .
"57": "0"
"58": .
"59": "1"
"60": '"'
"61": "\n"
"62": "}"
